# Generated by Django 5.0.6 on 2024-07-08 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_weightentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecondaryMuscleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("hombros", "Hombros"),
                            ("trapecios", "Trapecios"),
                            ("pecho", "Pecho"),
                            ("dorsal", "Dorsal"),
                            ("espalda alta", "Espalda Alta"),
                            ("triceps", "Tríceps"),
                            ("biceps", "Bíceps"),
                            ("abductor", "Abductor"),
                            ("gluteo", "Glúteo"),
                            ("cuadriceps", "Cuádriceps"),
                            ("abdominal", "Abdominal"),
                            ("lumbar", "Lumbar"),
                            ("gemelo", "Gemelo"),
                            ("femoral", "Femoral"),
                            ("antebrazo", "Antebrazo"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="exercise_images/"
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "main_muscle_group",
                    models.CharField(
                        choices=[
                            ("hombros", "Hombros"),
                            ("trapecios", "Trapecios"),
                            ("pecho", "Pecho"),
                            ("dorsal", "Dorsal"),
                            ("espalda alta", "Espalda Alta"),
                            ("triceps", "Tríceps"),
                            ("biceps", "Bíceps"),
                            ("abductor", "Abductor"),
                            ("gluteo", "Glúteo"),
                            ("cuadriceps", "Cuádriceps"),
                            ("abdominal", "Abdominal"),
                            ("lumbar", "Lumbar"),
                            ("gemelo", "Gemelo"),
                            ("femoral", "Femoral"),
                            ("antebrazo", "Antebrazo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "secondary_muscle_groups",
                    models.ManyToManyField(
                        blank=True, to="accounts.secondarymusclegroup"
                    ),
                ),
            ],
        ),
    ]
